"""
Data masking strategies for obfuscating sensitive fields in DataFrames.

Five strategies with distinct trade-offs:

- null: Replaces values with None. Guaranteed no leakage; destroys all utility.
- shuffle: Permutes values within a column. Preserves the marginal distribution
  of each column but destroys row-level linkage — and, critically, destroys
  the ability to join across tables if the shuffled column is a foreign key.
- impute: Replaces with fresh synthetic values from a caller-provided function.
  Realistic, zero leakage; requires a configured imputer per column.
- resample: Distribution-aware replacement for numeric columns. Fits (mean, std)
  from the existing column and draws new values from the same normal distribution.
  Familiar to anyone who has done bootstrap resampling — preserves the statistical
  shape without exposing actual values.
- hash: SHA-256 first 8 hex characters. Deterministic across runs, enabling
  cross-table joins on masked keys. Leaks value frequency and format; low-cardinality
  columns are vulnerable to dictionary attacks.

Use apply_masking to apply per-column strategies in a single call.
"""

import hashlib
from collections import defaultdict
from typing import Callable

import numpy as np
import pandas as pd


def mask_null(df: pd.DataFrame, columns: list[str]) -> pd.DataFrame:
    """
    Replace specified column values with None (NaN for numeric columns).

    The simplest masking strategy. Appropriate when downstream consumers must
    receive no representation of the original values, even statistical ones.

    Pros: Guaranteed no leakage. Simple to audit.
    Cons: Destroys all analytical utility. Cannot reconstruct any statistics.

    Args:
        df: Input DataFrame. Not modified in place.
        columns: Column names to null out.

    Returns:
        New DataFrame with specified columns set to None.

    Example:
        >>> masked = mask_null(customer_df, ["email", "phone"])
        >>> masked["email"].isna().all()
        True
    """
    masked_df = df.copy()
    for column in columns:
        masked_df[column] = None
    return masked_df


def mask_shuffle(
    df: pd.DataFrame, columns: list[str], generator: np.random.Generator
) -> pd.DataFrame:
    """
    Randomly permute values within each specified column.

    Values are shuffled independently per column, breaking row-level linkage
    while preserving the marginal distribution of each column. Note that if
    the shuffled column is a foreign key, shuffling severs the relationship
    to the referenced table — a customer_id that looked valid before the
    shuffle will point to the wrong customer after it.

    Pros: Preserves column-level statistics (mean, std, value frequency).
    Cons: Row-level linkage is destroyed. Cross-table joins on the shuffled
          column will silently return wrong results, not errors.

    Args:
        df: Input DataFrame. Not modified in place.
        columns: Column names to shuffle.
        generator: numpy random Generator for reproducible permutation.

    Returns:
        New DataFrame with values in specified columns permuted.

    Example:
        >>> gen = np.random.default_rng(42)
        >>> masked = mask_shuffle(customer_df, ["zip_code"], gen)
        >>> sorted(masked["zip_code"]) == sorted(customer_df["zip_code"])
        True
    """
    masked_df = df.copy()
    for column in columns:
        column_values = masked_df[column].values.copy()
        generator.shuffle(column_values)
        masked_df[column] = column_values
    return masked_df


def mask_impute(
    df: pd.DataFrame,
    columns: list[str],
    imputers: dict[str, Callable[[int], list]],
) -> pd.DataFrame:
    """
    Replace values in specified columns with freshly generated synthetic data.

    Each column requires a callable that accepts a row count and returns a list
    of replacement values. The replacement data can be generated by any function,
    including labforge's own generators, making this the most flexible strategy.

    Pros: Realistic values, no leakage of originals, preserves column type.
    Cons: Row-level and cross-column relationships are destroyed. Requires a
          configured imputer per column.

    Args:
        df: Input DataFrame. Not modified in place.
        columns: Column names to impute. Must all be keys in imputers.
        imputers: Dict mapping column name to a callable(n: int) -> list[Any].
                  The callable receives the number of rows and returns replacement
                  values.

    Returns:
        New DataFrame with specified columns replaced by synthetic values.

    Raises:
        ValueError: If a column in columns has no corresponding entry in imputers.

    Example:
        >>> def make_emails(n):
        ...     return [f"user{i}@example.com" for i in range(n)]
        >>> masked = mask_impute(df, ["email"], {"email": make_emails})
        >>> masked["email"].str.contains("@").all()
        True
    """
    masked_df = df.copy()
    n_rows = len(masked_df)
    for column in columns:
        if column not in imputers:
            raise ValueError(
                f"Column '{column}' has no imputer. "
                f"Provide a callable in the imputers dict."
            )
        masked_df[column] = imputers[column](n_rows)
    return masked_df


def mask_resample(
    df: pd.DataFrame, columns: list[str], generator: np.random.Generator
) -> pd.DataFrame:
    """
    Replace numeric column values by resampling from the column's empirical distribution.

    Fits (mean, std) from the existing column values and draws fresh values from
    generator.normal(mean, std, n), clipped to the original [min, max] range.
    This is bootstrap resampling of the empirical distribution: new values follow
    the same statistical shape as the originals without being the original values.

    Pros: Distribution-preserving, no real values exposed, familiar to anyone
          who has done bootstrap resampling or simulation.
    Cons: Leaks mean and std to anyone who can observe the masked data. Only
          valid for numeric columns.

    Args:
        df: Input DataFrame. Not modified in place.
        columns: Numeric column names to resample.
        generator: numpy random Generator for reproducible sampling.

    Returns:
        New DataFrame with specified columns replaced by resampled values.

    Raises:
        ValueError: If a specified column is not numeric.

    Example:
        >>> gen = np.random.default_rng(42)
        >>> masked = mask_resample(customer_df, ["age"], gen)
        >>> abs(masked["age"].mean() - customer_df["age"].mean()) < 10
        True
    """
    masked_df = df.copy()
    for column in columns:
        if not pd.api.types.is_numeric_dtype(masked_df[column]):
            raise ValueError(
                f"Column '{column}' is not numeric. "
                f"mask_resample only applies to numeric columns."
            )
        original_values = masked_df[column].dropna()
        column_mean = float(original_values.mean())
        column_std = float(original_values.std())
        column_min = float(original_values.min())
        column_max = float(original_values.max())

        resampled_values = generator.normal(column_mean, column_std, size=len(masked_df))
        masked_df[column] = np.clip(resampled_values, column_min, column_max)
    return masked_df


def mask_hash(
    df: pd.DataFrame, columns: list[str], salt: str = ""
) -> pd.DataFrame:
    """
    Replace values with the first 8 characters of their SHA-256 hash.

    Deterministic: the same input value always produces the same hash token,
    which allows masked data to be joined across tables without exposing originals.
    An optional salt increases resistance to precomputed dictionary attacks.

    Pros: Deterministic. Enables cross-table joins on masked keys.
    Cons: Leaks structural patterns (length, format, value frequency). Low-cardinality
          columns are vulnerable to dictionary attacks even with moderate compute.

    Args:
        df: Input DataFrame. Not modified in place.
        columns: Column names to hash.
        salt: Optional string prepended to each value before hashing.

    Returns:
        New DataFrame with specified columns replaced by 8-character hex tokens.

    Example:
        >>> masked = mask_hash(customer_df, ["customer_id"], salt="my-salt")
        >>> masked["customer_id"].str.len().eq(8).all()
        True
    """
    masked_df = df.copy()
    for column in columns:
        masked_df[column] = masked_df[column].apply(
            lambda value: hashlib.sha256(
                f"{salt}{value}".encode("utf-8")
            ).hexdigest()[:8]
        )
    return masked_df


def apply_masking(
    df: pd.DataFrame,
    mask_config: dict[str, str],
    generator: np.random.Generator,
    imputers: dict[str, Callable[[int], list]] | None = None,
    salt: str = "",
) -> pd.DataFrame:
    """
    Apply per-column masking strategies in a single call.

    Dispatches to the appropriate masking function for each column based on
    the strategy string in mask_config. All strategies are validated before
    any masking is applied (fail-fast on unknown strategy names).

    Valid strategy strings: "null", "shuffle", "impute", "resample", "hash".

    Args:
        df: Input DataFrame. Not modified in place.
        mask_config: Dict mapping column name to strategy string.
                     E.g., {"email": "hash", "phone": "null", "age": "resample"}.
        generator: numpy random Generator, used by shuffle and resample strategies.
        imputers: Dict mapping column name to imputer callable, required for any
                  column using the "impute" strategy. Defaults to {}.
        salt: Salt string for the hash strategy. Defaults to empty string.

    Returns:
        New DataFrame with all specified masking strategies applied.

    Raises:
        ValueError: If an unknown strategy string is provided.
        ValueError: If "impute" is requested but no imputer is provided.

    Example:
        >>> gen = np.random.default_rng(42)
        >>> config = {
        ...     "phone": "null",
        ...     "city": "shuffle",
        ...     "age": "resample",
        ...     "customer_name": "impute",
        ...     "customer_id": "hash",
        ... }
        >>> imputers = {"customer_name": lambda n: ["Anonymous"] * n}
        >>> masked = apply_masking(df, config, gen, imputers=imputers)
    """
    if imputers is None:
        imputers = {}

    strategy_dispatch: dict[str, Callable] = {
        "null": lambda masked_df, columns: mask_null(masked_df, columns),
        "shuffle": lambda masked_df, columns: mask_shuffle(masked_df, columns, generator),
        "resample": lambda masked_df, columns: mask_resample(masked_df, columns, generator),
        "impute": lambda masked_df, columns: mask_impute(masked_df, columns, imputers),
        "hash": lambda masked_df, columns: mask_hash(masked_df, columns, salt=salt),
    }

    unknown_strategies = [
        f"'{column}' → '{strategy}'"
        for column, strategy in mask_config.items()
        if strategy not in strategy_dispatch
    ]
    if unknown_strategies:
        raise ValueError(
            f"Unknown masking strategies: {unknown_strategies}. "
            f"Valid strategies: {sorted(strategy_dispatch)}"
        )

    columns_by_strategy: dict[str, list[str]] = defaultdict(list)
    for column, strategy in mask_config.items():
        columns_by_strategy[strategy].append(column)

    masked_df = df.copy()
    for strategy, columns in columns_by_strategy.items():
        masked_df = strategy_dispatch[strategy](masked_df, columns)

    return masked_df
